# Generated by Django 5.2 on 2025-04-30 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the type of instrument (max 30 characters)', max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Enter the brand name of the instrument (max 30 characters)', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Brand name must be at least 2 characters long.')])),
                ('model', models.CharField(help_text='Enter the model name of the instrument (max 20 characters)', max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Model name must be at least 2 characters long.')])),
                ('description', models.TextField(help_text='Provide a detailed description of the instrument.')),
                ('year', models.IntegerField(help_text='Enter the year the instrument was manufactured.', validators=[django.core.validators.MinValueValidator(1900, 'Year must be 1900 or later.'), django.core.validators.MaxValueValidator(2100, 'Year must be 2100 or earlier.')])),
                ('image', models.ImageField(help_text='Upload an image of the instrument.', upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the instrument (max 10 digits, 2 decimal places).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Price must be greater than zero.')])),
                ('stock', models.IntegerField(help_text='Enter the number of items in stock.', validators=[django.core.validators.MinValueValidator(0, 'Stock cannot be negative.')])),
                ('category', models.ManyToManyField(help_text='Select one or more categories for this instrument.', to='store.instrumentcategory')),
                ('type', models.ManyToManyField(help_text='Select one or more types for this instrument.', to='store.instrumenttype')),
            ],
        ),
    ]
