# Generated by Django 5.2 on 2025-04-30 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcategory',
            name='description',
            field=models.TextField(help_text='Provide a description of the instrument category.'),
        ),
        migrations.AlterField(
            model_name='instrumentcategory',
            name='name',
            field=models.CharField(help_text='Enter the name of the instrument category (max 30 characters)', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Category name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(30, 'Category name cannot exceed 30 characters.')]),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='brand',
            field=models.CharField(help_text='Enter the brand name of the instrument (max 30 characters)', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Brand name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(30, 'Brand name cannot exceed 30 characters')]),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='model',
            field=models.CharField(help_text='Enter the model name of the instrument (max 20 characters)', max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Model name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(20, 'Model name cannot exceed 20 characters')]),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='description',
            field=models.TextField(help_text='Provide a description of the instrument type.'),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='name',
            field=models.CharField(help_text='Enter the type of instrument (max 30 characters)', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Category name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(30, 'Category name cannot exceed 30 characters.')]),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, help_text='Enter the manufacturer origin country', max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Manufacturer country must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(50, 'Manufacturer country cannot exceed 50 characters.')]),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(help_text='Type the manufacturer description'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(help_text='Enter a name of the manufacturer', max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Manufacturer name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(50, 'Manufacturer name cannot exceed 50 characters.')]),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, help_text='Enter the URL of the manufacturer website', null=True, validators=[django.core.validators.URLValidator(message="Enter a valid URL including 'http[s]://'.")]),
        ),
    ]
