# Generated by Django 5.2 on 2025-04-30 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_instrumentcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentcategory',
            options={'verbose_name_plural': 'Instrument Categories'},
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Enter the brand name of the instrument (max 30 characters)', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Brand name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(30, 'Brand name cannot exceed 30 characters')])),
                ('model', models.CharField(help_text='Enter the model name of the instrument (max 20 characters)', max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Model name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(20, 'Model name cannot exceed 20 characters')])),
                ('description', models.TextField(help_text='Provide a detailed description of the instrument.')),
                ('year', models.IntegerField(help_text='Enter the year the instrument was manufactured.', validators=[django.core.validators.MinValueValidator(1900, 'Year must be 1900 or later.'), django.core.validators.MaxValueValidator(2100, 'Year must be 2100 or earlier.')])),
                ('image', models.ImageField(help_text='Upload an image of the instrument.', upload_to='instruments/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the instrument (max 10 digits, 2 decimal places).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Price must be greater than zero.')])),
                ('stock', models.IntegerField(help_text='Enter the number of items in stock.', validators=[django.core.validators.MinValueValidator(0, 'Stock cannot be negative.')])),
                ('category', models.ManyToManyField(help_text='Select one or more categories for this instrument.', to='store.instrumentcategory')),
                ('type', models.ManyToManyField(help_text='Select one or more types for this instrument.', to='store.instrumenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='Instruments',
        ),
    ]
