# Generated by Django 5.2 on 2025-05-01 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_instrument_slug_alter_instrumentcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='slug',
            field=models.SlugField(help_text='Enter a unique slug for the instrument (max 100 characters)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Slug must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(100, 'Slug cannot exceed 100 characters.')]),
        ),
        migrations.AlterField(
            model_name='instrumentcategory',
            name='slug',
            field=models.SlugField(help_text='Enter a unique slug for the category (max 50 characters)', unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Slug must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(50, 'Slug cannot exceed 50 characters.')]),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='slug',
            field=models.SlugField(help_text='Enter a unique slug for the type (max 50 characters)', unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Slug must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(50, 'Slug cannot exceed 50 characters.')]),
        ),
    ]
