# Generated by Django 5.2 on 2025-04-30 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_instrumentcategory_options_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='color',
            field=models.CharField(blank=True, help_text='Enter the color of the instrument (max 20 characters)', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Color name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(20, 'Color name cannot exceed 20 characters.')]),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='year',
            field=models.IntegerField(blank=True, help_text='Enter the year the instrument was manufactured.', null=True, validators=[django.core.validators.MinValueValidator(1900, 'Year must be 1900 or later.'), django.core.validators.MaxValueValidator(2100, 'Year must be 2100 or earlier.')]),
        ),
    ]
