# Generated by Django 5.2 on 2025-05-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_instrument_slug_alter_instrumentcategory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='type',
        ),
        migrations.AddField(
            model_name='instrument',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Select one or more types for this instrument.', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.instrumenttype'),
        ),
    ]
