# Generated by Django 5.2 on 2025-04-30 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_instrument_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='model',
            field=models.CharField(help_text='Enter the model name of the instrument (max 100 characters)', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Model name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(100, 'Model name cannot exceed 100 characters')]),
        ),
    ]
