# Generated by Django 5.2 on 2025-05-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatically generated slug.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='instrumentcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatically generated slug.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatically generated slug.', max_length=100, unique=True),
        ),
    ]
