# Generated by Django 5.2 on 2025-05-07 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_instrument_slug_alter_instrumentcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='type',
            field=models.ForeignKey(default=None, help_text='Select one or more types for this instrument.', on_delete=django.db.models.deletion.CASCADE, to='store.instrumenttype'),
        ),
    ]
